### ISSUE TITLE
Cobblestone Generator duplication glitch

### ISSUE THREAD

**Issue by Einhornyordle** [Kashdeya/Tiny-Progressions#126]
Note: I've only tried this while playing the Stoneblock Modpack, but I'm sure that it will work with other modpacks too.

Every Cobblestone Generator has an internal item slot that contains the generated cobblestones that you'll receive when you right click it. I used TC's Crafting Station to make it visible:

![setup](https://user-images.githubusercontent.com/47315090/52533166-242b2c00-2d30-11e9-9df6-d1fa3f75092c.png)

![the slot](https://user-images.githubusercontent.com/47315090/52533168-33aa7500-2d30-11e9-82c4-0dd7f434106e.png)

If you now somehow manage to place any item inside that slot, the generator starts generating the item instead of cobblestone:

![diamond generator](https://user-images.githubusercontent.com/47315090/52533170-3a38ec80-2d30-11e9-8f61-ce173ac01eb9.png)

This even works with (enchanted) tools (if you use a chest):

![enchanted tools](https://user-images.githubusercontent.com/47315090/52533202-a582be80-2d30-11e9-9b21-3c2371e8f972.png)

And modded Items:

![avaritia](https://user-images.githubusercontent.com/47315090/52533212-b92e2500-2d30-11e9-9679-a8c795db04f4.png)

**Comment by GenDeathrow** [comment]
Make sure when you report you add the version number of the mod. This got fixed in v3.3.32. This is kind of a two or 3 mod issue. We had some bad code that allowed any item that got into the slot to get duped, but on our side nothing was allowed to be put into that slot. So we can figure out if jei or tinkers was forcing the item into the slot, and not following the slot's rules. 

A lot of packs are just going to be behind on updates.
