### ISSUE TITLE
Updating this on SkyFactory 3 displays error messages in-world

### ISSUE THREAD

**Issue by Layarion** [Kashdeya/Tiny-Progressions#128]
just spent like 3 hours going through each mod on the Twitch app on Skyfactory 3, updating 1 mod at a time, and then running the game to see if anything breaks.

after that tedious amount of time, there are only 4 mods left that break or display some sort of "something not right" messages on world load. this is one of them. i'm wondering if there are any dependencies that versions higher than 1.5.1 don't have? on 1.5.1 i don't get these errors.

here is a link, of a screenshot of the messages i'm getting from this mod. are these things i can ignore or should i roll back to the version of this mod that ships with sky factory?

https://i.imgur.com/CFtq2Tn.png

error: could not resolve

**Comment by GenDeathrow** [comment]
This is because you have updated mods you weren't suppose too. The error your getting is from specific recipes that sky factory made. This isn't a mod issue nor is it really a pack issue. mods change some which can break old packs.. Version on packs is important. most mods can update no problem.. But some mods change small things which can break packs if updated.

**Comment by Darkosto** [comment]
I'm going to hop in on this one, too:

This is not a mod issue, it's a scripts issue you created when updating mods, Scripts are looking for items that no longer exist due to ID changes or because they were simply removed in later versions. 

I made SkyFactory 3 with certain mod versions and scripts rely on those. Unless you are absolutely certain on what you are doing then you should not update mods. GenDeathrow is correct, it's not a pack issue either and really isn't something that should be reported. It's the same concept of altering a car under warranty and expecting the dealership to fix your car.

**Comment by GenDeathrow** [comment]
/\ Explains way better than me.
