### ISSUE TITLE
Inconsistent Growth Crystal Tier 2 Range

### ISSUE THREAD

**Issue by BrainInBlack** [Kashdeya/Tiny-Progressions#14]
**Mod Version:** 1.10.2-1.0.17

It seems that the Tier 2 variant of the Growth Crystal has inconsistent ranges between the watering (9x9) and growth (11x11) part. Don't know if this is intentional, to account for automated farms that exceed the "standard" 9x9 range.

**Comment by GenDeathrow** [comment]
To be honest that the 9x9 is a vanilla mechanic that is actually controlled by the farmland itself,and not the growth crystal. But the growth crystal worked on a 11x11 ,before it changed to act as a water source.

**Comment by BrainInBlack** [comment]
So, it is an intended mechanic?

Because it is affecting non connected Farmland as well and even my tree farm.

_Edit: added clarification_

**Comment by GenDeathrow** [comment]
I couldnt tll ya that because I didnt initially program those.  But the 11x11 was intentional. The 9x9 watering cant be changed (or easily),  because its a vanilla mechanic. Im sure we an consider looking into it, But no promises.

**Comment by Kashdeya** [comment]
This has been fixed in the newest update.

**Comment by Zaflis** [comment]
Just a sidenote; if tier 2 is 9x9, how does tier 1 growth crystal work. I've looked up with google but i find nothing. It has no tooltip. Can i put water source under farming station and the tier 1 growth crystal under it to hope it boost 7x7? My current guess is that i should be putting 1 growth crystal under every dirt block, but i could be wrong?

**Comment by Kashdeya** [comment]
@Zaflis if you have no tooltips on the tier 1 growth crystal then you are on a very very old version. all growth crystals work the same for the most part. tier 1 checks 2 above or 2 below, tier 2 is a water source and checks 5 above or below, tier 3 is a water source and checks 10 above or 10 below. 

But like I said if you do not have tooltips on the first growth crystal you need to update the pack or update the mod seeing that tooltips have been there since around v1.0.21
