### ISSUE TITLE
More of a Question, Not an Issues

### ISSUE THREAD

**Issue by BedrockLegends** [Kashdeya/Tiny-Progressions#152]
I am looking to disable some items in Tiny Progressions for 1.15.2, but I dont see any way to do that and I really dont want to use datapacks for it. in 1.12, we had config options for that

**Comment by GenDeathrow** [comment]
Hi, so everything has been flatten post 1.12 It actually easier to use a mod like craft tweaker, JEI and the likes to remove items from a game or change a recipe. The only reason we used configs before was because you use to be limited on the amount of items you could have in a pack.. so TP had configs to remove items from the game to help that. There is no long a hard limit on items/blocks anymore and in turn no need to have over bloated configs. Especially now that configs are handled in one single toml file (Not by my choice).
