### ISSUE TITLE
Little Error - hardness of Reinforced glass (Texture)

### ISSUE THREAD

**Issue by Lightone** [Kashdeya/Tiny-Progressions#17]
when you have the crystal in your hand (the glass is clear) but is you put in the world change a black and appear clear when is destroyed.

Test with the last version (tinyprogressions-1.10.2-1.0.19)

![2017-01-14_12 06 43](https://cloud.githubusercontent.com/assets/2113099/21957170/d83e0392-da5e-11e6-94d0-3f6f9c316d27.png)

**Comment by Kashdeya** [comment]
I can not duplicate the problem. are you using a texture pack?

![2017-01-14_13 08 57](https://cloud.githubusercontent.com/assets/3231637/21957398/b56f1f76-da5a-11e6-84c8-cf8bb2a1b8b0.png)

**Comment by Lightone** [comment]
no, i found the problem (OptiFine).

without optiFine the crystal look fine, like you show in your pic, but if i use OptiFine, the crystal change to black, is strange the other crystal (or glass) with alpha view dont have that problem, only this one. 

the dirty glass look fine dont have any problem.

you can check with optiFine ?.

**Comment by Kashdeya** [comment]
Sorry but Optifine is not supported and will never be.

**Comment by aelfwyne** [comment]
Have the same problem - found the issue here.

I'm not sure why so many devs blatantly REFUSE to even consider testing with Optifine. For many, even with higher end video cards, Optifine makes a huge difference in game performance.

**Comment by GenDeathrow** [comment]
Because Optifine blatantly CHANGES core files. Which makes it extremely difficult for us mod devs to actually make fixes that work good for forge and optifine. We program in forge api not Optifine. Optifine bugs should be reported to Optifine not a mod dev. And if there is a fix or change they recommend than we can add it. If and only if it works forge. Since more ppl use forge.
