### ISSUE TITLE
Cobblestone Generator x Transfer Nodes (Extra Utilities 2 Mod)

### ISSUE THREAD

**Issue by em48126** [Kashdeya/Tiny-Progressions#65]
I was watching a YouTube Video that showed an individual who was able to link the Extra Utilities 2 Transfer Node to the CobbleGen while on the SkyFactory3 modpack.  When I tried to mimic, it no longer worked.  Is there an update in the future to change this?

**Comment by Kashdeya** [comment]
You will have to ask the Devs of Extra utilities 2. As of right now we are using the forge inventory check to see if there is a inventory block around our cobblegens. If EU2 does not use the forge version which it sounds like they don't they will need to change their mod. as we have removed legacy support due to conflicts and do not plan to add it back in as that is a step backwards.
