### ISSUE TITLE
Harvesting my wheat with a Scythe crashed the client

### ISSUE THREAD

**Issue by laconicdesigns** [Kashdeya/Tiny-Progressions#87]
It worked once, then after that it doesn't seem to want to work. I haven't tried it on a full 3x3 ripe crop yet, but if there is grass or water in the 3x3, it crashes for sure. I have a crash report.
[crash-2018-02-02_23.37.55-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1691396/crash-2018-02-02_23.37.55-client.txt)

**Comment by laconicdesigns** [comment]
I just noticed that my current Scythe has -2 durability on it. I'd bet that has something to do with it. I'm not sure why it hasn't broken.
![2018-02-02_23 49 39](https://user-images.githubusercontent.com/195022/35763158-d22f350e-0873-11e8-8d97-5277e78d6a6e.png)

**Comment by joselitosn** [comment]
The game crashes before the item is destroyed, so you keep the item even if it crashes.

The bugfix is simple, but since the mod is getting an upgrade, there are no new releases since October 2017.

Since we don't know when there will be a new version, to fix it you are going to have to compile it yourself. It's assumed you have Git and Java JRE installed and configured, if not download it first.

Open the command line and execute the following commands:

    git clone -n https://github.com/Kashdeya/Tiny-Progressions.git
    git checkout 6bb26f3b5044c9af82118701bf6edcf2f7043b9d
    cd Tiny-Progressions

Now you will have to change one line in the file "src\main\java\com\kashdeya\tinyprogressions\items\scythes\ScytheMain.java"

Find the line 93 or the one containing the following:

    playerIn.setHeldItem(hand, null);

and change into:

    playerIn.setHeldItem(hand, ItemStack.EMPTY);

Now execute the following command inside the Tiny-Progressions main folder:

    gradlew build

There will be now two files inside "build\libs" folder.  Copy the one without "sources" in it's name to your Minecraft mods folder, replacing the existing one.
